#
# Main pl9k config
POWERLEVEL9K_MODE="nerdfont-complete"
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(vi_mode dir vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status command_execution_time virtualenv vaulture time)
POWERLEVEL9K_VI_INSERT_MODE_STRING=$'\uF054'
POWERLEVEL9K_VI_COMMAND_MODE_STRING=$'\uF142'
POWERLEVEL9K_VI_MODE_NORMAL_FOREGROUND="red"
POWERLEVEL9K_STATUS_OK="false"
POWERLEVEL9K_DIR_SHOW_WRITABLE="true"
POWERLEVEL9K_JAVA_ICON=$'\UE256'

#
# pl9k SHORTEN_DIR setup
POWERLEVEL9K_SHORTEN_DIR_DEFAULT_LENGTH=2
POWERLEVEL9K_SHORTEN_DIR_LENGTH=$POWERLEVEL9K_SHORTEN_DIR_DEFAULT_LENGTH
POWERLEVEL9K_SHORTEN_DELIMITER=' '$'\uF141'' '
toggle-shorten-dir() {
    [[ $POWERLEVEL9K_SHORTEN_DIR_LENGTH = $POWERLEVEL9K_SHORTEN_DIR_DEFAULT_LENGTH ]] && \
        POWERLEVEL9K_SHORTEN_DIR_LENGTH=100 || \
        POWERLEVEL9K_SHORTEN_DIR_LENGTH=$POWERLEVEL9K_SHORTEN_DIR_DEFAULT_LENGTH

    zle reset-prompt
}
zle -N toggle-shorten-dir
